---
title: "CI"
author: "Xu Zhihao"
date: "9/1/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tcltk2) 
library(parallel)
library(MASS)

f = function(x){
  return(dnorm(x,mean=0,sd=1))
}
g = function(x){
  return(dnorm(x,mean=0.5,sd=1))
}

# index: the affected censor, K: the number of all the censors
generateN = function(mu,size=100){
  column = rnorm(size,mean=mu,sd=1)
  return(as.matrix(column))
}

# n = number of infected censor, K = Number of Censor
simulate_topr = function(mu,r=10,a=46.55,StopT=10000000){
  W = rep(0,100)
  m = 0
  size0=100
  data = matrix(generateN(mu,size=100*size0),nrow=100,byrow=FALSE)
  
  allW = matrix(rep(NA,10000),100)
  # allT = c()
  while (m < StopT) {
    m = m + 1
    if (m %% size0 == 0) {
      data=cbind(data,matrix(generateN(mu,size=100*size0),nrow=100,byrow=FALSE))
      allW = cbind(allW,matrix(rep(NA,10000),100))
    }
    
    W = W + log(g(data[,m])/f(data[,m]))
    W = ifelse(W>0,W,0)
    allW[,m] = W
    
    s = sort(W,decreasing = TRUE,index.return =TRUE)
    w = s$x[1:r]
    r.index = s$ix[1:r]
    
    t = sum(w)
    if (t > a){
      break
    }
  }
  data = data[,1:m]
  allW = allW[,1:m]
  muHat = apply(data,1,mean)
  
  # data: the whole dataset, n: stopping time, 
  # W: the vector of all the W statistic, r.index: selected index
  result <- list(data=data, StopT=m, W=W, allW = allW,r.index = r.index, 
                 a0=sum(w), mu=mu, muHat=muHat, r=r, a=a)
  return(result)
}
topr = simulate_topr(mu=c(rep(0.5,5),rep(0,95)))
```




```{r}
computeWObs = function(topr,i){
  W = rep(0,100)
  allsumR = rep(NA,topr$StopT)
  for (m in 1:topr$StopT) {
    newMu = topr$mu
    newMu[i] = 0
    W = W + log(g(topr$data[,m]-newMu)/f(topr$data[,m]-newMu))
    W = ifelse(W>0,W,0)
    s = sort(W,decreasing = TRUE,index.return =TRUE)
    allsumR[m] = sum(s$x[1:topr$r])
  }
  return(allsumR)
}
computeWGen = function(sim,i){
  W = rep(0,100)
  for (m in 1:sim$StopT) {
    newMu = sim$mu
    newMu[i] = 0
    W = W + log(g(sim$data[,m]-newMu)/f(sim$data[,m]-newMu))
    W = ifelse(W>0,W,0)

  }
  s = sort(W,decreasing = TRUE,index.return =TRUE)
  return( sum(s$x[1:sim$r]))
}
```

```{r}
ST = c()
mu = c(rep(1,2),rep(0.5,2),rep(0,96))
for (i in 1:100){
  topr = simulate_topr(mu,r=10,a=46.55*2)
  ST = c(ST,topr$StopT)
}
mean(ST)
```

```{r}
mu = c(rep(1.5,2),rep(0.75,2),rep(0,96))
topr = simulate_topr(mu,r=10,a=46.55*2)
ii = 0
for (i in topr$r.index){
  ii = ii +1
  p = rep(0,200)
  mu0 = topr$mu
  mu0[3] = 0
  for (k in 1:200){
    sim = simulate_topr(mu=mu0, StopT=topr$StopT, r=10)
    # if (sim$StopT<topr$StopT){
    #   p[k] = 1
    # } else if ((sim$StopT==topr$StopT)&(simW>ta0[sim$StopT])){
    #   p[k] = 1
    # } else{
    #   p[k] = 0
    # }
    if (sort(apply(sim$data,1,mean))[101-ii]>apply(topr$data[,1:sim$StopT],1,mean)[i]){
      p[k] = 1
    }
  }
  p=sum(p)/200
  cat(i,":\t",p,"\n")
}
```






```{r}
mu = c(rep(0.5,5),rep(0,95))
topr = simulate_topr(mu,r=10)
ii = 0
for (i in topr$r.index){
  ta0 = computeWObs(topr,i)
  ii = ii +1
  p = rep(0,100)
  mu0 = topr$mu
  mu0[i] = 0
  for (k in 1:100){
    sim = simulate_topr(mu=mu0, StopT=topr$StopT, r=10)
    simW = computeWGen(sim,i)
    # if (sim$StopT<topr$StopT){
    #   # print("Early Stop")
    #   p[k] = 1
    # } else if ((sim$StopT==topr$StopT)&(simW>ta0[sim$StopT])){
    #   p[k] = 1
    # } else{
    #   p[k] = 0
    # }
    if (simW>ta0[sim$StopT]){
      p[k] = 1
    }
  }
  p=sum(p)/100
  cat(i,":\t",p,"\n")
}

```


```{r}
P = rep(NA,5*100)
pb <- tkProgressBar("进度","已完成 %", 0, 100)
size = 100
for (aaa in 1:size){
  ###
  mu = c(rep(0.5,5),rep(0,95))
  topr = simulate_topr(mu,r=10)
  ii = 0
  for (i in c(1:5)){
  # for (i in topr$r.index){
    ta0 = computeWObs(topr,i)
    ii = ii +1
    p = rep(0,100)
    mu0 = topr$mu
    mu0[i] = 0
    for (k in 1:100){
      sim = simulate_topr(mu=mu0, StopT=topr$StopT, r=10)
      simW = computeWGen(sim,i)
      if (simW>ta0[sim$StopT]){
        p[k] = 1
      }
    }
    p=sum(p)/100
    P[(aaa-1)*5+ii] = p
    # cat(i,":\t",p,"\n")
  }
  ###
  info<- sprintf("已完成 %d%%", round(aaa*100/size))
  setTkProgressBar(pb, aaa*100/size, sprintf("进度 (%s)", info),info)
}
close(pb)
```






































```{r}
computeF = function(topr,theta,tindex,alpha){
  R = topr$W[tindex]
  mu = topr$mu
  mu[tindex] = theta
  Ri = c()
  i = 1
  while (i <= 200){
    Xi = simulate_topr(mu)
    ri = Xi$W[tindex]
    i = i+1
    Ri = c(Ri,ri)
  }
  Ri = sort(Ri)
  muL = Ri[200*(1-alpha)]
  return(R - muL)
}

CI = function(topr,tindex,q){
  theta = 100
  b0 = 0
  f0 = computeF(topr,theta=b0,tindex,alpha=q)
  if (f0<=0){
    return(0)
  }
  a = topr$muHat[tindex] ##<0
  fa = computeF(topr,theta=a,tindex,alpha=q)
  b = a - 2*1/sqrt(topr$StopT)
  fb = computeF(topr,theta=b,tindex,alpha=q)
  while (TRUE){
    if (fb<=0){
      b = b - 0.5*1/sqrt(topr$StopT)
      if (b<=0){
        return(0)
      }
      fb = computeF(topr,theta=b,tindex,alpha=q)
    } else{
      break
    }
  }
  
  oldTheta = theta
  theta = (b*fa - a*fb)/(fa-fb)
  k=1
  while ((abs(theta-oldTheta)>=0.01)&(k<=5)){
    f0 = computeF(topr,theta=theta,tindex,alpha=q)
    if (f0<0){
      a = theta
      fa = f0
    }else{
      b = theta
      fb = f0
    }
    oldTheta = theta
    theta = (b*fa - a*fb)/(fa-fb)
    k = k+1
  }
  return(theta)
}
```



```{r}
topr = simulate_topr(mu=c(rep(0.5,5),rep(0,95)))
LB = c();size=100
pb <- tkProgressBar("进度","已完成 %", 0, 100)
for (i in 1:100){
  lb = CI(topr,tindex=i,q=0.2)
  LB = c(LB,lb)
  
  info<- sprintf("已完成 %d%%", round(i*100/size))
  setTkProgressBar(pb, i*100/size, sprintf("进度 (%s)", info),info)
}
close(pb)
sum(LB<=topr$mu)
```



```{r}
CR = c()
power = c()
mu = c(rep(0.5,5),rep(0,95))
for ( ii in 1:100){
  topr = simulate_topr(mu,r=10)
  Xbar = apply(topr$data,1,mean)
  CR = c(CR,1 - pnorm(Xbar,mean=topr$mu,sd=1/sqrt(topr$StopT)))
  power = c(power, 1 - pnorm(Xbar[c(1:5)],mean=0,sd=1/sqrt(topr$StopT)))
}
```

