---
title: "Resampling"
author: "Xu Zhihao"
date: "11/6/2019"
output: pdf_document
---

```{r}
library(tcltk2) 
library(doParallel)
library(foreach)
library(MASS)

f = function(x){
  return(dnorm(x,mean=0,sd=1))
}
g = function(x){
  return(dnorm(x,mean=0.5,sd=1))
}

# index: the affected censor, K: the number of all the censors
generateN = function(mu,size=100){
  column = rnorm(size,mean=mu,sd=1)
  return(as.matrix(column))
}

# n = number of infected censor, K = Number of Censor
simulate_topr = function(n,mug=0.5,r=10,a=46.55,rho=0){
  mu = c(rep(mug,n),rep(0,100-n))
  W = rep(0,100)
  m = 0
  
  Sigma = matrix(rep(rho,100*100),100)
  diag(Sigma) = 1
  
  size0 = 100
  if (rho==0){
    data = matrix(generateN(mu,size=100*size0),nrow=100,byrow=FALSE)
  } else{
    data = matrix(mvrnorm(size0,mu,Sigma),nrow=100,byrow = TRUE)
  }
  
  allW = c()
  # allT = c()
  while (TRUE) {
    m = m + 1
    
    if (m %% size0 == 0) {
      if (rho==0){
        data=cbind(data,matrix(generateN(mu,size=100*size0),nrow=100,byrow=FALSE))
      } else{
        data = cbind(data,matrix(mvrnorm(size0,mu,Sigma),nrow=100,byrow = TRUE))
      }
    }
    
    W = W + log(g(data[,m])/f(data[,m]))
    W = ifelse(W>0,W,0)
    allW = cbind(allW,W)
    
    s = sort(W,decreasing = TRUE,index.return =TRUE)
    w = s$x[1:r]
    r.index = s$ix[1:r]
    
    t = sum(w)
    if (t > a){
      break
    }
    # allT = cbind(allT,apply(data,1,mean)/(1/sqrt(m)))
  }
  data = data[,1:m]
  muHat = apply(data,1,mean)
  sdHat = apply(data,1,sd)
  T0 = muHat/(sdHat/sqrt(m))
  
  # data: the whole dataset, n: stopping time, 
  # W: the vector of all the W statistic, r.index: selected index
  result <- list(data=data,allW=allW,StopT=m,W=W,T0=T0,r.index = r.index, sig=n, mug=mug, rho=rho, muHat=muHat,sdHat=sdHat)
  return(result)
}
```


```{r}
selectSample = function(data){
  sam = matrix(sample(topr$StopT,topr$StopT*99,replace = TRUE),nrow=99)
  for (i in 1:99){
    data[i,] = data[i,sam[i,]]
  }
  return(data)
}
```


```{r}
indTao = function(topr,tindex,t0,a=46.55,r=10){
  # data = topr$data[-tindex,]
  # sam = sample(t,topr$StopT,replace = TRUE)
  # data = data[,sam]
  # # data = selectSample(data)
  # x = rnorm(topr$StopT,mean=0,sd=1) 
  # data = rbind(x,data)
  
  # mu = c(rep(topr$mug,topr$sig),rep(0,100-topr$sig))
  mu = topr$muHat
  mu[tindex] = 0
  data = matrix(rnorm(100*topr$StopT,mean=mu,sd=1),100)
  
  allW = c()
  W = rep(0,100)
  for (j in 1:topr$StopT){
    W = W + log(g(data[,j])/f(data[,j]))
    W = ifelse(W>0,W,0)
    allW = cbind(allW,W)

    s = sort(W,decreasing = TRUE,index.return =TRUE)
    w = s$x[1:r]
    r.index = s$ix[1:r]
    
    t = sum(w)
    if (t > a){
      return(1)
      # break
    }
  }
  t
  # return(mean(data[1,])/(sd(data[1,])/sqrt(j)))
  return(0)
}
```




```{r}
topr = simulate_topr(n=1,mug=0.5)
topr$StopT
p = c()
for (i in topr$r.index){
  ind = c()
  for (b in 1:100){
    tao = indTao(topr,tindex = i,t0=topr$StopT/2)
    ind = c(ind,tao)
  }
  p = c(p,mean(ind))
}
p = cbind(topr$r.index,p)
p = cbind(p,p.adjust(p[,2],method="BH"))
p
```



<!-- ```{r} -->
<!-- library(doParallel) -->
<!-- cl <- makeCluster(1) -->
<!-- registerDoParallel(cl) -->

<!-- system.time( -->
<!-- a <- foreach(1:1000,.combine=rbind) %dopar% indTao(topr,tindex = 1) -->
<!-- ) -->
<!-- stopCluster(cl) -->
<!-- ``` -->

```{r}
find0 = function(x){
  for (i in length(x):2){
    if ((x[i]==0)&(x[i-1]!=0)){
      return(i)
    }
  }
  return(0)
}
```



```{r}
#sam = sample(topr$StopT,replace = TRUE)
#sam = 1:topr$StopT
W1 = 0
for (j in 1:100){
  sam = sample(topr$StopT,replace = TRUE)
  a = log(g(topr$data[61,sam])/f(topr$data[61,sam]))
  s = 0
  for (i in 1:topr$StopT){
    s = s + a[i]
    if (s<0){
      s = 0
    }
  }
  W1 = c(W1,s)
}
sum(sort(W1)[91:100])
```


```{r}
# topr = simulate_topr(n=1,mug=0.5)
# mean(topr$W[2:100])

# x = rnorm(topr$StopT,mean=0,sd=1)
# a = log(g(x)/f(x))
# s = 0
# for (i in 1:topr$StopT){
#   s = s + a[i]
#   if (s<0){
#     s = 0
#   }
# }
# s0 = s
# s0
topr = simulate_topr(n=1,mug=0.5)
count = 0
for (t in 2:100){
  W2 = 0
  for (j in 1:100){
    sam = sample(topr$StopT,topr$StopT,replace = TRUE)
    x = topr$data[t,]
    x1 = x[sam]
    a = log(g(x1)/f(x1))
    s = 0
    for (i in 1:topr$StopT){
      s = s + a[i]
      if (s<0){
        s = 0
      }
    }
    W2 = c(W2,s)
  }
  count = count + ifelse(mean(W2)>topr$W[t],1,0)
}
count
```
































```{r}
resamplePvalue = function(topr){
  p = c()
  for (i in topr$r.index){
    ind = c()
    for (b in 1:100){
      tao = indTao(topr,tindex = i)
      ind = c(ind,tao)
    }
    p = c(p,mean(ind))
  }
  p = cbind(topr$r.index,p)
  p = cbind(p,p.adjust(p[,2],method="BH"))
  
  fdr01 = sum((p[,3]<0.1)&(p[,1] %in% seq(1,topr$sig) == FALSE))/sum(p[,3]<0.1)
  power01 = sum((p[,3]<0.1)&(p[,1] %in% seq(1,topr$sig)))/topr$sig
  
  fdr02 = sum((p[,3]<0.2)&(p[,1] %in% seq(1,topr$sig) == FALSE))/sum(p[,3]<0.2)
  power02 = sum((p[,3]<0.2)&(p[,1] %in% seq(1,topr$sig)))/topr$sig
  
  result = list(p=p,fdr01=fdr01,power01=power01,fdr02=fdr02,power02=power02)
  return(result)
}

```



```{r}
FDR01=c()
POWER01=c()
FDR02=c()
POWER02=c()

pb <- tkProgressBar("进度","已完成 %", 0, 100)
size = 10
sig=1
p = c()
for (i in 1:size){
  topr = simulate_topr(n=sig,mug=0.5,rho=0.5)
  RP = resamplePvalue(topr)
  p = c(p,RP$p[(RP$p[,1]%in%c(1:sig)==FALSE),2])
  FDR01 = c(FDR01,RP$fdr01)
  POWER01 = c(POWER01,RP$power01)
  
  FDR02 = c(FDR02,RP$fdr02)
  POWER02 = c(POWER02,RP$power02)
  
  info<- sprintf("已完成 %d%%", round(i*100/size))  
  setTkProgressBar(pb, i*100/size, sprintf("进度 (%s)", info),info)
}
close(pb)
```


```{r}
FDR01[is.nan(FDR01)] = 0
mean(FDR01)
mean(POWER01)
FWER01 = sum(FDR01>0)/length(FDR01)
FWER01
```



```{r}
FDR02[is.nan(FDR02)] = 0
mean(FDR02)
mean(POWER02)
FWER02 = sum(FDR02>0)/length(FDR02)
FWER02
```
