---
title: "PvalueCI New Statistic"
author: "xzh"
date: "10/07/2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tcltk2) 
library(parallel)
library(MASS)

f = function(x){
  return(dnorm(x,mean=0,sd=1))
}
g = function(x){
  return(dnorm(x,mean=0.5,sd=1))
}

# index: the affected censor, K: the number of all the censors
generateN = function(mu,size=100){
  column = rnorm(size,mean=mu,sd=1)
  return(as.matrix(column))
}

# n = number of infected censor, K = Number of Censor
simulate_topr = function(n,mug=0.5,r=10,a=46.55,rho=0){
  mu = c(rep(mug,n),rep(0,100-n))
  W = rep(0,100)
  m = 0
  
  Sigma = matrix(rep(rho,100*100),100)
  diag(Sigma) = 1
  
  size0 = 100
  if (rho==0){
    data = matrix(generateN(mu,size=100*size0),nrow=100,byrow=FALSE)
  } else{
    data = matrix(mvrnorm(size0,mu,Sigma),nrow=100,byrow = TRUE)
  }
  
  allW = c()
  # allT = c()
  while (TRUE) {
    m = m + 1
    
    if (m %% size0 == 0) {
      if (rho==0){
        data=cbind(data,matrix(generateN(mu,size=100*size0),nrow=100,byrow=FALSE))
      } else{
        data = cbind(data,matrix(mvrnorm(size0,mu,Sigma),nrow=100,byrow = TRUE))
      }
    }
    
    W = W + log(g(data[,m])/f(data[,m]))
    W = ifelse(W>0,W,0)
    allW = cbind(allW,W)
    
    s = sort(W,decreasing = TRUE,index.return =TRUE)
    w = s$x[1:r]
    r.index = s$ix[1:r]
    
    t = sum(w)
    if (t > a){
      break
    }
    # allT = cbind(allT,apply(data,1,mean)/(1/sqrt(m)))
  }
  data = data[,1:m]
  muHat = apply(data,1,mean)
  sdHat = apply(data,1,sd)
  T0 = muHat/(sdHat/sqrt(m))
  
  # data: the whole dataset, n: stopping time, 
  # W: the vector of all the W statistic, r.index: selected index
  result <- list(data=data,StopT=m,W=W,allW=allW,T0=T0,r.index = r.index, sig=n, mug=mug, rho=rho, muHat=muHat,sdHat=sdHat)
  return(result)
}

# t = Stopping time T, K = Number of censor
simulate_topr_GlobalNullT = function(t,mu,r=10,a=46.55,rho=0){
  W = rep(0,100)
  m = 0
  
  Sigma = matrix(rep(rho,100*100),100)
  diag(Sigma) = 1
  
  if (rho==0){
    data = matrix(generateN(mu,size=100*t),nrow=100,byrow=FALSE)
  } else{
    data = matrix(mvrnorm(t,mu,Sigma),nrow=100,byrow = TRUE)
  }
  
  while (TRUE){
    m = m + 1
    
    if (m %% t == 0) {
      
      if (rho==0){
        data=cbind(data,matrix(generateN(mu,size=100*t),nrow=100,byrow=FALSE))
      } else{
        data = cbind(data,matrix(mvrnorm(t,mu,Sigma),nrow=100,byrow = TRUE))
      }
      
    }
    
    W = W + log(g(data[,m])/f(data[,m]))
    W = ifelse(W>0,W,0)
    
    s = sort(W,decreasing = TRUE,index.return =TRUE)
    w = s$x[1:r]
    r.index = s$ix[1:r]

    if (sum(w) > a){
      break
    }
  }
  
  # s = sort(W,decreasing = TRUE,index.return =TRUE)
  # w = s$x[1:r]
  # r.index = s$ix[1:r]
  
  data = data[,1:m]
  T0 = apply(data,1,mean)/(apply(data,1,sd)/sqrt(m))
  
  result <- list(eStop=m,W=W,T0=T0,r.index = r.index)# data=data,
  return(result)
}


simulate_topr_KnockoffGlobalNull_BT = function(topr,mu,rejIndex,tindex,r=10,B = 200,a = 46.55){
  indicator = c()
  b = 0
  while (b <= B){
    Wr = simulate_topr_GlobalNullT(topr$StopT,mu, r = 10, a = 46.55,rho=topr$rho)
    index = Wr$r.index[which(Wr$r.index %in% rejIndex==FALSE)]
    T0 = Wr$T0[index]
    T0 = matrix(rep(T0,length(tindex)),length(tindex),byrow = TRUE)
    
    ind = ifelse(T0 > topr$T0[tindex],1,0)
    
    indicator = cbind(indicator, ind)
    b = b + length(index)
  }
  return(indicator)
}
```


```{r}
# t = Stopping time T, K = Number of censor
simulate_topr_GlobalNullT_Stepdown = function(t,K,ObsW,rindex,r=10,a=46.55,rho=0){
  W = rep(0,K)
  m = 0
  # data = c()
  r = r - (100-K)
  ObsW = ObsW[rindex,]
  mu = rep(0,K)
  
  Sigma = matrix(rep(rho,K*K),K)
  diag(Sigma) = 1
  
  if (rho==0){
    data = matrix(generateN(mu,size=K*t),nrow=K,byrow=FALSE)
  } else{
    data = matrix(mvrnorm(t,mu,Sigma),nrow=K,byrow = TRUE)
  }
  
  while (m < t){
    m = m + 1
    
    W = W + log(g(data[,m])/f(data[,m]))
    W = ifelse(W>0,W,0)
    s = sort(W,decreasing = TRUE,index.return=TRUE)
    w = s$x[1:r]
    if (is.null(rindex)){
      t0 = sum(w)
    } else if (length(rindex)==1){
      t0 = sum(w)+ObsW[t]
    } else {
      t0 = sum(w)+sum(ObsW[,t])
    }
    
    if (t0 > a){
      break
    }
  }
  
  data = data[,1:m]
  T0 = apply(data,1,mean)/(apply(data,1,sd)/sqrt(m))
  
  result <- list(W=w,T0=T0[s$ix[1:r]],StopT=m)
  return(result)
}


simulate_topr_GlobalNullT_B_Stepdown = function(topr,rindex,tindex,B = 200,K = 100,a = 46.55){
  indicator = c()
  b = 0
  while (b<=B){
    s = simulate_topr_GlobalNullT_Stepdown(t=topr$StopT,ObsW=topr$allW,rindex=rindex,K = K, r = 10, a = 46.55, rho=topr$rho)
    # print(s$StopT)
    indicator = c(indicator, ifelse(s$T0>topr$T0[tindex],1,0))
    b = b+length(s$T0)
  }
  return(indicator)
}

knockoff = function(topr,q0,r=10,a=46.55){
  muNull = rep(0,100)
  Sigma = matrix(rep(topr$rho,100*100),100)
  diag(Sigma) = 1
  s = min(1,2*min(eigen(Sigma)$values))
  SigmaDummy = Sigma - (Sigma-diag(rep(s,100))) %*% solve(Sigma) %*% (Sigma-diag(rep(s,100)))
  
  m = 0
  W = rep(0,100)
  data = c()
  
  while (m<topr$StopT){
    m = m + 1
    
    if (topr$rho==0){
      data=cbind(data,generateN(mu))
    } else{
      muDummy = (Sigma-diag(rep(s,100))) %*% solve(Sigma) %*% topr$data[,m]
      data = cbind(data,matrix(mvrnorm(1,muDummy,Sigma),nrow=100,byrow = TRUE))
    }
    
    W = W + log(g(data[,m])/f(data[,m]))
    W = ifelse(W>0,W,0)
    
    W0 = c(W,topr$allW[,m])
    s0 = sort(W0,decreasing = TRUE,index.return =TRUE)
    w = s0$x[1:r]

    if (sum(w) > a){
      break
    }
  }
  
  data = data[,1:m]
  T0Dummy = apply(data,1,mean)/(apply(data,1,sd)/sqrt(m))
  W = topr$T0 - T0Dummy
  
  for (t in seq(0,10,0.01)){
    Spt = sum(W> t)
    Smt = sum(W<(-t))
    q = (1 + Smt)/Spt
    if (q <= q0){
      break
    } else if (t == 10){
      t = 1000
    }
  }
  
  reject_index = which(W > t)
  return(reject_index)
}

Stepdown = function(topr,q=0.2){
  rindex = c()
  K0 = 100
  q = 0.2
  pvalue = c()
  index = topr$r.index[sort(topr$T0[topr$r.index],index.return=TRUE,decreasing = TRUE)$ix]
  for (i in index){
    ind = simulate_topr_GlobalNullT_B_Stepdown(topr,rindex=rindex,i,K=K0)
    p = sum(ind)/length(ind)
    pvalue = c(pvalue,p)
    if (p <= q/(K0-90)){
      K0 = K0-1
      rindex = c(rindex,i)
    } else{
      break
    }
  }
  
  result = list(p=pvalue,rindex=rindex)
  return(result)
}
```



```{r}
knockoffAcp = function(topr){
  rejIndex = c()
  while(length(rejIndex)==0){
    rejIndex0 = knockoff(topr,q0=0.2)
    rejIndex1 = Stepdown(topr,q=0.2)$rindex
    rejIndex = union(rejIndex0,rejIndex1)
  }

  mu = rep(0,100)
  mu[rejIndex] = topr$muHat[rejIndex]
  
  # mu = rep(0,100)
  # mu[1:topr$sig] = topr$mug
  # rejIndex = c(1:topr$sig)
  
  rejT = intersect(topr$r.index,rejIndex)

  p=c()
  for (i in rejT){
    mu0 = mu
    mu0[i] = 0
    ind = simulate_topr_KnockoffGlobalNull_BT(topr,mu0,rejIndex,tindex=i)
    p = rbind(p,c(i,sum(ind)/length(ind)))
  }
  # p = rbind(p,c(1,0))
  
  tindex = setdiff(topr$r.index,rejT)
  ind = simulate_topr_KnockoffGlobalNull_BT(topr,mu,rejIndex,tindex=tindex)
  p0 = cbind(tindex,apply(ind,1,sum)/dim(ind)[2])
  p = rbind(p,p0)
  # p = p[sort(p[,2],index.return=TRUE)$ix,]
  p=cbind(p,p.adjust(p[,2],method="BH"))
  p = cbind(p,topr$muHat[p[,1]])
  
  fdr01 = sum((p[,3]<0.1)&(p[,1] %in% seq(1,topr$sig) == FALSE))/sum(p[,3]<0.1)
  power01 = sum((p[,3]<0.1)&(p[,1] %in% seq(1,topr$sig)))/topr$sig
  
  fdr02 = sum((p[,3]<0.2)&(p[,1] %in% seq(1,topr$sig) == FALSE))/sum(p[,3]<0.2)
  power02 = sum((p[,3]<0.2)&(p[,1] %in% seq(1,topr$sig)))/topr$sig
  
  result = list(p=p,fdr01=fdr01,power01=power01,fdr02=fdr02,power02=power02)
  return(result)
}
```



```{r}
FDR01=c()
POWER01=c()
FDR02=c()
POWER02=c()

pb <- tkProgressBar("进度","已完成 %", 0, 100)
size = 100
sig=20
p = c()
for (i in 1:size){
  topr = simulate_topr(n=sig,mug=0.5,rho=0.5)
  KA = knockoffAcp(topr)
  p = c(p,KA$p[(KA$p[,1]%in%c(1:sig)==FALSE),2])
  FDR01 = c(FDR01,KA$fdr01)
  POWER01 = c(POWER01,KA$power01)
  
  FDR02 = c(FDR02,KA$fdr02)
  POWER02 = c(POWER02,KA$power02)
  
  info<- sprintf("已完成 %d%%", round(i*100/size))  
  setTkProgressBar(pb, i*100/size, sprintf("进度 (%s)", info),info)
}
close(pb)
```


```{r}
FDR01[is.nan(FDR01)] = 0
mean(FDR01)
mean(POWER01)
FWER01 = sum(FDR01>0)/length(FDR01)
FWER01
```



```{r}
FDR02[is.nan(FDR02)] = 0
mean(FDR02)
mean(POWER02)
FWER02 = sum(FDR02>0)/length(FDR02)
FWER02
```


  | # affected | $\mu_g$ |  $q$  |  FDR  |  POWER  | FWER  |
  | :--------: | :-----: | :---: | :---: | :-----: | :---: |
  |      1     |   0.5   |  0.1  | 0.085 |  1      | 0.16  |
  |      1     |   0.5   |  0.2  | 0.168 |  1      | 0.3   |
  |      5     |   0.5   |  0.1  | 0.070 |  0.626  | 0.25  |  
  |      5     |   0.5   |  0.2  | 0.169 |  0.762  | 0.57  |
  |      10    |   0.5   |  0.1  | 0.066 |  0.439  | 0.3   |
  |      10    |   0.5   |  0.2  | 0.103 |  0.569  | 0.52  |
  |      20    |   0.5   |  0.1  | 0.015 |  0.227  | 0.07  |
  |      20    |   0.5   |  0.2  | 0.033 |  0.325  | 0.18  |
  
  
  
rho = 0.5  
  | :--------: | :-----: | :---: | :---: | :-----: | :---: |
  |      5     |   0.5   |  0.1  | 0.035 |  0.612  | 0.11  |
  |      5     |   0.5   |  0.2  | 0.068 |  0.802  | 0.23  |
  |      10    |   0.5   |  0.1  | 0.017 |  0.365  | 0.105 |
  |      10    |   0.5   |  0.2  | 0.027 |  0.597  | 0.168 |
  
  
  
  
  
  
  
  
  

```{r}
# t = Stopping time T, K = Number of censor
simulate_topr_CI = function(mu,t,r=10,a=46.55){
  W = rep(0,100)
  m = 0
  data = matrix(generateN(mu,size=100*t),nrow=100,byrow=FALSE)
  
  while(TRUE){
  # for (i in 1:t){
    m = m + 1
    
    if (m %% t == 0) {
      data=cbind(data,matrix(generateN(mu,size=100*t),nrow=100,byrow=FALSE))
    }
    
    W = W + log(g(data[,m])/f(data[,m]))
    W = ifelse(W>0,W,0)
    
    s = sort(W,decreasing = TRUE,index.return =TRUE)
    w = s$x[1:r]
    r.index = s$ix[1:r]

    t0 = sum(w)
    if (t0 > a){
      break
    }
  }
  
  data = data[,1:m]
  Xbar = apply(data,1,mean)
  
  result <- list(data=data,StopTb=m,W=W,r.index = r.index,Xbar = Xbar)
  return(result)
}
```



  
```{r}
computeF = function(topr,theta,mu,tindex,alpha){
  R = (topr$muHat[tindex]-theta)/(topr$sdHat[tindex]/sqrt(topr$StopT))
  mu[tindex] = theta
  Ri = c()
  i = 1
  while (i <= 200){
    Xi = simulate_topr_CI(mu,t=topr$StopT)
    if (tindex%in%Xi$r.index==FALSE){
      next
    }
    ri = (Xi$Xbar[tindex]-theta)/(sd(Xi$data[tindex,])/sqrt(Xi$StopTb))
    i = i+1
    Ri = c(Ri,ri)
  }
  Ri = sort(Ri)
  muL = Ri[200*(1-alpha)]
  return(R - muL)
}


CI = function(topr,tindex,mu,q){
  theta = 100
  a = topr$muHat[tindex] ##<0
  fa = computeF(topr,theta=a,mu=mu,tindex,alpha=q)
  b = a - 2*1/sqrt(topr$StopT)
  fb = computeF(topr,theta=b,mu=mu,tindex,alpha=q)
  while (TRUE){
    if (fb<=0){
      # print(b)
      b = b - 0.5*1/sqrt(topr$StopT)
      if (b<=0){
        return(0)
      }
      fb = computeF(topr,theta=b,mu=mu,tindex,alpha=q)
    } else{
      break
    }
  }
  
  oldTheta = theta
  theta = (b*fa - a*fb)/(fa-fb)
  k=1
  while ((abs(theta-oldTheta)>=0.01)&(k<=5)){
    f0 = computeF(topr,theta=theta,mu=mu,tindex,alpha=q)
    if (f0<0){
      a = theta
      fa = f0
    }else{
      b = theta
      fb = f0
    }
    oldTheta = theta
    theta = (b*fa - a*fb)/(fa-fb)
    k = k+1
  }
  return(theta)
}
```


 
```{r}
computeF2 = function(topr,theta,mu,tindex,alpha){
  # R = (mean(topr$data[tindex,])-theta)/(sd(topr$data[tindex,])/sqrt(topr$StopT))
  mu[tindex] = theta
  i = 1
  ind = c()
  while (i <= 200){
    Xi = simulate_topr_CI(mu,t=topr$StopT)
    if (tindex%in%Xi$r.index==FALSE){
      next
    }
    ri = (Xi$Xbar[tindex]-theta)/(sd(Xi$data[tindex,])/sqrt(Xi$StopTb))
    tar = (mean(topr$data[tindex,])-theta)/(sd(topr$data[tindex,])/sqrt(topr$StopT))
    ind = c(ind,ifelse(ri>tar,1,0))
    i = i+1
  }
  return(-mean(ind)+alpha)
}

CI2 = function(topr,tindex,mu,q){
  theta = 100
  a = mean(topr$data[tindex,]) ##<0
  fa = computeF2(topr,theta=a,mu=mu,tindex,alpha=q)
  b = a - 2*1/sqrt(topr$StopT)
  fb = computeF2(topr,theta=b,mu=mu,tindex,alpha=q)
  while (TRUE){
    if (fb<=0){
      b = b - 0.5*1/sqrt(topr$StopT)
      if (b<=0){
        return(0)
      }
      fb = computeF2(topr,theta=b,mu=mu,tindex,alpha=q)
    } else{
      break
    }
  }
  
  oldTheta = theta
  theta = (b*fa - a*fb)/(fa-fb)
  k=1
  while ((abs(theta-oldTheta)>=0.005)&(k<=10)){
    f0 = computeF2(topr,theta=theta,mu=mu,tindex,alpha=q)
    if (f0<0){
      a = theta
      fa = f0
    }else{
      b = theta
      fb = f0
    }
    oldTheta = theta
    theta = (b*fa - a*fb)/(fa-fb)
    k = k+1
  }
  return(theta)
}
```




```{r}
knockoffAcpCIFCR = function(topr,q){
  rejIndex = c()
  while(length(rejIndex)==0){
    rejIndex0 = knockoff(topr,q0=0.2)
    rejIndex1 = Stepdown(topr,q=0.2)$rindex
    rejIndex = union(rejIndex0,rejIndex1)
  }

  mu = rep(0,100)
  mu[rejIndex] = topr$muHat[rejIndex]
  
  rejT = intersect(topr$r.index,rejIndex)

  p=c()
  for (i in rejT){
    mu0 = mu
    mu0[i] = 0
    ind = simulate_topr_KnockoffGlobalNull_BT(topr,mu0,rejIndex,tindex=i)
    p = rbind(p,c(i,sum(ind)/length(ind)))
  }
  
  tindex = setdiff(topr$r.index,rejT)
  ind = simulate_topr_KnockoffGlobalNull_BT(topr,mu,rejIndex,tindex=tindex)
  p0 = cbind(tindex,apply(ind,1,sum)/dim(ind)[2])
  p = rbind(p,p0)
  p=cbind(p,p.adjust(p[,2],method="BH"))
  
  Nr = sum(p[,2]<q)
  q0 = Nr * q/10
  
  LB = c()
  for (i in p[,1]){
    if (p[p[,1]==i][2]>q0){
      lb = 0
    } else{
      mu0 = mu
      mu0[i] = 0
      lb = CI(topr,tindex = i,mu=mu0,q0)
    }
    LB = c(LB,lb)
  }
  
  p = cbind(p,LB)
  mu = c(rep(topr$mug,topr$sig),rep(0,100-topr$sig))
  p = cbind(p,mu[p[,1]])
  p = cbind(p,topr$muHat[p[,1]])
  colnames(p) = c("index","p-value","p-valueBH","CILowerBond","trueMu","muHat")
  return(p)
}


knockoffAcpCI = function(topr,q){
  # rejIndex = c()
  # while(length(rejIndex)==0){
  #   rejIndex0 = knockoff(topr,q0=0.2)
  #   rejIndex1 = Stepdown(topr,q=0.2)$rindex
  #   rejIndex = union(rejIndex0,rejIndex1)
  # }
  # 
  # mu = rep(0,100)
  # mu[rejIndex] = topr$muHat[rejIndex]
  
  rejIndex = c(1:topr$sig)
  mu = rep(0,100)
  mu[rejIndex] = topr$mug
  
  rejT = intersect(topr$r.index,rejIndex)

  p=c()
  for (i in rejT){
    mu0 = mu
    mu0[i] = 0
    ind = simulate_topr_KnockoffGlobalNull_BT(topr,mu0,rejIndex,tindex=i)
    p = rbind(p,c(i,sum(ind)/length(ind)))
  }
  
  tindex = setdiff(topr$r.index,rejT)
  ind = simulate_topr_KnockoffGlobalNull_BT(topr,mu,rejIndex,tindex=tindex)
  p0 = cbind(tindex,apply(ind,1,sum)/dim(ind)[2])
  p = rbind(p,p0)
  p=cbind(p,p.adjust(p[,2],method="BH"))
  
  LB = c()
  for (i in p[,1]){
    if (p[p[,1]==i][2]>q){
      lb = 0
    } else{
      mu0 = mu
      mu0[i] = 0
      lb = CI(topr,tindex = i,mu=mu0,q)
    }
    LB = c(LB,lb)
  }
  
  p = cbind(p,LB)
  mu = c(rep(topr$mug,topr$sig),rep(0,100-topr$sig))
  p = cbind(p,mu[p[,1]])
  p = cbind(p,topr$muHat[p[,1]])
  colnames(p) = c("index","p-value","p-valueBH","CILowerBond","trueMu","muHat")
  return(p)
}
```

 | # affected | $\mu_g$ |  $q$  |   CR  |
 | :--------: | :-----: | :---: | :---: |
 |     10     |   0.5   |  0.1  | 0.892 |
 |     10     |   0.5   |  0.2  | 0.827 |
 |     5      |   0.5   |  0.1  | 0.913 |
 |     5      |   0.5   |  0.2  | 0.807 |
 |     1      |   0.5   |  0.1  | 0.929 |
 |     1      |   0.5   |  0.2  | 0.819 |
 |     10     |   0.8   |  0.1  | 0.885 |
 |     10     |   0.8   |  0.2  | 0.776 |  true distribution 0.81 
 |     5      |   0.8   |  0.1  | 0.919 |
 |     5      |   0.8   |  0.2  | 0.81  | 
 |     1      |   0.8   |  0.1  | 0.923 |  
 |     1      |   0.8   |  0.2  | 0.857 |    0.822
 |     10     |   0.3   |  0.1  | 0.898 |
 |     10     |   0.3   |  0.2  | 0.813 |
 |     5      |   0.3   |  0.1  | 0.923 |
 |     5      |   0.3   |  0.2  | 0.811 |
 |     1      |   0.3   |  0.1  | 0.929 |
 |     1      |   0.3   |  0.2  | 0.849 |


```{r}
estimateFCR = function(n,mug,q,size=100){
  pb <- tkProgressBar("进度","已完成 %", 0, 100)
  FCR = c()
  pNull = c()
  for (i in 1:size){
    topr = simulate_topr(n=n,mug=mug,rho=0)
    
    p = knockoffAcpCIFCR(topr,q=q)
    # cr = ifelse(p[,5]>=p[,4],1,0)
    fcr = sum((p[,5]<p[,4])&(p[,2]<q))/sum((p[,2]<q))
    FCR = c(FCR,fcr)
    
    pNull = c(pNull,p[,2][which(p[,1] %in% c(1:n)==FALSE)])
  
    info<- sprintf("已完成 %d%%", round(i*100/size))  
    setTkProgressBar(pb, i*100/size, sprintf("进度 (%s)", info),info)
  }
  close(pb)
  result = list(mFCR=mean(FCR),p0=pNull,FCR=FCR)
  return(result)
}

estimateCR = function(n,mug,q,size=100){
  pb <- tkProgressBar("进度","已完成 %", 0, 100)
  pNull = c()
  CR = c()
  for (i in 1:size){
    topr = simulate_topr(n=n,mug=mug,rho=0)
    
    p = knockoffAcpCI(topr,q=q)
    cr = ifelse(p[,5]>=p[,4],1,0)
    CR = c(CR,cr)
    pNull = c(pNull,p[,2][which(p[,1] %in% c(1:n)==FALSE)])
  
    info<- sprintf("已完成 %d%%", round(i*100/size))  
    setTkProgressBar(pb, i*100/size, sprintf("进度 (%s)", info),info)
  }
  close(pb)
  result = list(mCR=mean(CR),p0=pNull,CR=CR)
  return(result)
}
```



```{r}
r1 = estimateCR(n=10,mug=0.3,q=0.1,size=100)
r2 = estimateCR(n=5,mug=0.3,q=0.2,size=100)
r3 = estimateCR(n=5,mug=0.3,q=0.1,size=100)
r4 = estimateCR(n=1,mug=0.3,q=0.2,size=100)
```




```{r}
r1$mCR
r2$mCR
r3$mCR
r4$mCR
```


















```{r}
knockoffAcp2 = function(topr){
  
  # rejIndex0 = knockoff(topr,q0=0.2)
  # rejIndex0=c()
  # rejIndex1 = Stepdown(topr,q=0.2)$rindex
  # rejIndex = union(rejIndex0,rejIndex1)
  # 
  # if (length(rejIndex)==1){
  #   muHat = mean(topr$data[rejIndex,])
  # } else{
  #   muHat = apply(topr$data[rejIndex,],1,mean)
  # }
  # mu = rep(0,100)
  # mu[rejIndex] = muHat
  # 
  # print(rejIndex)
  # print(muHat)
  
  mu = rep(0,100)
  rejIndex = c()
  
  tindex = topr$r.index
  ind = simulate_topr_KnockoffGlobalNull_BT(topr,mu,rejIndex,tindex=tindex)
  p = cbind(tindex,apply(ind,1,mean))
  return(p)
}

simulate_topr_KnockoffGlobalNull_BT2 = function(topr,mu,rejIndex,tindex,r=10,B = 200,a = 46.55){
  indicator1 = c()
  indicator2 = c()
  b = 0
  count0 = 0
  count1 = 0
  while (b <= B){
    # print(i)
    Wr = simulate_topr_GlobalNullT(topr$StopT,mu, r = 10, a = 46.55)
    index = Wr$r.index[which(Wr$r.index %in% rejIndex==FALSE)]
    T0 = Wr$T0[index]
    T0 = matrix(rep(T0,length(tindex)),length(tindex),byrow = TRUE)
    
    if (Wr$eStop < topr$StopT){
      # print(Wr$eStop)
      count0 = count0 + 1
      if (length(tindex)==1){
        tar = mean(topr$data[tindex,1:Wr$eStop])/(sd(topr$data[tindex,1:Wr$eStop])/sqrt(Wr$eStop))
      } else{
        tar = apply(topr$data[tindex,1:Wr$eStop],1,mean)/(apply(topr$data[tindex,1:Wr$eStop],1,sd)/sqrt(Wr$eStop))
      }
  
      ind = ifelse(T0 > tar,1,0)
      indicator1 = cbind(indicator1, ind)
    } else {
      count1 = count1 + 1
      ind = ifelse(T0 > topr$T0[tindex],1,0)
      indicator2 = cbind(indicator2, ind)
    }
    
    if (count0==0){
      indicator1 = cbind(rep(0,length(topr$r.index)))
    } 
    if (count1==0){
      indicator2 = cbind(rep(0,length(topr$r.index)))
    } 
    # # 无提前停
    # ind = ifelse(T0 > topr$T0[tindex],1,0)
    b = b + length(index)
  }
  
  result = list(ind1 = indicator1, ind2 = indicator2)
  return(result)
}
```


<!-- ```{r} -->
<!-- p01 = c() -->
<!-- p02 = c() -->
<!-- TT = c() -->
<!-- pb <- tkProgressBar("进度","已完成 %", 0, 100) -->
<!-- size=50 -->
<!-- for (i in 1:size){ -->
<!--   topr = simulate_topr(n=9) -->
<!--   # rejIndex0 = knockoff(topr,q0=0.2) -->
<!--   # rejIndex1 = Stepdown(topr)$rindex -->
<!--   # rejIndex = union(rejIndex0,rejIndex1) -->
<!--   #  -->
<!--   # if (length(rejIndex)==1){ -->
<!--   #   muHat = mean(topr$data[rejIndex,]) -->
<!--   # } else{ -->
<!--   #   muHat = apply(topr$data[rejIndex,],1,mean) -->
<!--   # } -->
<!--   # mu = rep(0,100) -->
<!--   # mu[rejIndex] = muHat -->
<!--   mu = rep(0,100) -->
<!--   mu[1:9] = 0.5 -->
<!--   rejIndex = c(1:9) -->

<!--   tindex = topr$r.index -->

<!--   ind = simulate_topr_KnockoffGlobalNull_BT(topr,mu,rejIndex,tindex=tindex) -->
<!--   if (sum(apply(ind$ind1,1,mean)==0)!=10){ -->
<!--     p1 = cbind(tindex,apply(ind$ind1,1,mean)) -->
<!--     p01 = c(p01,p1[,2][p1[,1]%in%c(1:9)==FALSE]) -->
<!--   } -->

<!--   if (sum(apply(ind$ind2,1,mean)==0)!=10){ -->
<!--     p2 = cbind(tindex,apply(ind$ind2,1,mean)) -->
<!--     p02 = c(p02,p2[,2][p2[,1]%in%c(1:9)==FALSE]) -->
<!--   } -->



<!--   info<- sprintf("已完成 %d%%", round(i*100/size)) -->
<!--   setTkProgressBar(pb, i*100/size, sprintf("进度 (%s)", info),info) -->
<!-- } -->
<!-- close(pb) -->
<!-- hist(p01) -->
<!-- hist(p02) -->
<!-- ``` -->
